export const COMMAND = {
	LOAD: "LOAD",
	CHANGE_SELECTED_DATE: "CHANGE_SELECTED_DATE",
	AGGREGATE_BY_DAY: "AGGREGATE_BY_DAY",
	AGGREGATE_BY_MONTH: "AGGREGATE_BY_MONTH",
	AGGREGATE_BY_YEAR: "AGGREGATE_BY_YEAR"
};
